name: "TMDb Trailers"
guid: "69104C31-D23F-4040-B99C-8913C09751D6"
version: "10"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "crobibero"
overview: "Watch trailers from TMDb"
imageUrl: "https://raw.githubusercontent.com/crobibero/jellyfin-plugin-tmdb-trailers/master/Jellyfin.Plugin.Tmdb.Trailers/Images/jellyfin-plugin-tmdb.png"
description: >
  Watch trailers from TMDb

category: "Channels"
artifacts:
  - "Jellyfin.Plugin.Tmdb.Trailers.dll"
  - "TMDbLib.dll"
  - "AngleSharp.dll"
  - "CliWrap.dll"
  - "YoutubeExplode.dll"
  - "YoutubeExplode.Converter.dll"
changelog: |-
  - Fixes applied (#23) @m33ts4k0z
